language: node_js #選擇語言

node_js: stable #選擇版本

cache:
  directories:
    - "node_modules"

install:
  - yarn

#要執行的程式
script:
  - hexo clean # 清除
  - hexo generate # 生成

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  email: jd615645@gmail.com
  name: jd615645
  on:
    branch: master

notifications:
  email:
    on_failure: always